## template: jinja
#cloud-config

#
# (c) Copyright IBM Corp. 2021
# (c) Copyright Instana Inc.
#

package_update: true
package_upgrade: true
package_reboot_if_required: true

apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - debian-keyring
  - debian-archive-keyring
  - docker-ce
  - docker-ce-cli
  - containerd.io

runcmd:
  - systemctl start docker && systemctl enable docker
  - curl -L "https://github.com/docker/compose/releases/download/2.15.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
  - gcloud auth configure-docker --quiet
  - docker run --detach --name instana-agent --volume /var/run:/var/run --volume /run:/run --volume /dev:/dev --volume /sys:/sys --volume /var/log:/var/log --privileged --net=host --pid=host --ipc=host  --env="INSTANA_AGENT_ENDPOINT=${INSTANA_AGENT_ENDPOINT}" --env="INSTANA_AGENT_ENDPOINT_PORT=${INSTANA_AGENT_ENDPOINT_PORT}" --env="INSTANA_AGENT_KEY=${INSTANA_AGENT_KEY}" --env="INSTANA_AGENT_ZONE=${INSTANA_AGENT_ZONE}" "${INSTANA_AGENT_IMAGE}"

final_message: "The system is finally up, after $UPTIME seconds"
