timeout: '3000s'
images:
  - 'gcr.io/$PROJECT_ID/instana-agent-docker:$_FLAVOR-$COMMIT_SHA'

substitutions:
  _FLAVOR: 'dynamic'
  _ARCH: x86_64

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret=instana-qa-instana-agent-docker-prs > download_key'
  - name: 'docker'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        echo ${INSTANA_AGENT_KEY} > download_key
        DOCKER_BUILDKIT=1 docker build --no-cache \
          --build-arg $_ARCH
          --pull $_FLAVOR/ ${cacheFlag} \
          --secret id=download_key,src=download_key \
          --label "version=${releaseVersion}" \
          -t gcr.io/$PROJECT_ID/instana-agent-docker:$_FLAVOR-$COMMIT_SHA
        rm download_key
