timeout: '3000s'
images:
  - 'gcr.io/$PROJECT_ID/instana-agent-docker:$_FLAVOR-$SHORT_SHA'

substitutions:
  _FLAVOR: 'dynamic'

steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'gcloud secrets versions access latest --secret=instana-qa-instana-agent-docker-prs > agent_key.txt'
  - name: 'docker'
    entrypoint: /bin/sh
    args:
      - '-c'
      - |
        docker build -t gcr.io/$PROJECT_ID/instana-agent-docker:$_FLAVOR-$SHORT_SHA \
          --no-cache \
          --build-arg FTP_PROXY="$$( cat agent_key.txt )" \
          $_FLAVOR/
