---
# see https://concourse-ci.org/pipelines.html
resource_types:
  - name: codebuild
    type: registry-image
    source:
      repository: cedricziel/concourse-codebuild-resource
      tag: "0.1.14"
  - name: gcs-resource
    type: registry-image
    source:
      repository: frodenas/gcs-resource
resources:
  - name: instana-agent-docker-git
    type: git
    icon: github
    source:
      uri: https://github.com/instana/instana-agent-docker.git
      branch: ((branch))
      ignore_paths:
        - README.md
  - name: build-bundle
    type: s3
    icon: zip-disk
    source:
      bucket: instana-agent-images-codebuild
      versioned_file: context.zip
      access_key_id: ((codebuild-key.key_id))
      secret_access_key: ((codebuild-key.key_secret))
      region_name: us-west-2
      skip_download: true
  - name: codebuild-dynamic
    type: codebuild
    icon: aws
    source:
      project: instana-agent-images-s390x
      region: us-west-2
      access_key_id: ((codebuild-key.key_id))
      secret_access_key: ((codebuild-key.key_secret))
  - name: codebuild-static
    type: codebuild
    icon: aws
    source:
      project: instana-agent-images-s390x
      region: us-west-2
      access_key_id: ((codebuild-key.key_id))
      secret_access_key: ((codebuild-key.key_secret))
  - name: agent-dynamic-aarch64
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/instana-agent-docker
      tag: ubi-latest-dynamic-aarch64
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: agent-static-aarch64
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/instana-agent-docker
      tag: ubi-latest-static-aarch64
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: agent-dynamic-x86
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/instana-agent-docker
      tag: ubi-latest-dynamic-x86
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: agent-static-x86
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/instana-agent-docker
      tag: ubi-latest-static-x86
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: agent-dynamic-s390x
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/instana-agent-docker
      tag: ubi-latest-dynamic-s390x
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
  - name: agent-static-s390x
    type: registry-image
    icon: docker
    source:
      repository: gcr.io/instana-agent-qa/instana-agent-docker
      tag: ubi-latest-static-s390x
      username: _json_key
      password: ((project-berlin-tests-gcp-instana-qa))
jobs:
#  - name: self-update
#    max_in_flight: 1
#    plan:
#      - get: instana-agent-docker-git
#        trigger: true
#      - set_pipeline: self
#        file: instana-agent-docker-git/pipeline.yml
  - name: prepare-build-bundle
    public: true
    plan:
      - get: instana-agent-docker-git
        trigger: true
        # passed: [ self-update ]
      - task: package-build-bundle
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
          inputs:
            - name: instana-agent-docker-git
              path: .
          run:
            path: bash
            args:
              - -c
              - |
                date
                apt-get update
                apt-get install -yqq zip unzip
                #zip -r target/context.zip . --exclude @buildtools/codebuild/exclude.lst
                zip -r target/context.zip .
          outputs:
            - name: target
      - put: build-bundle
        params:
          file: target/context.zip

  - name: x86-build
    public: true
    plan:
      - get: instana-agent-docker-git
        trigger: true
        passed: [ prepare-build-bundle ]
      - get: build-bundle
        trigger: true
        passed: [ prepare-build-bundle ]
      - load_var: s3-artifact-version
        file: build-bundle/version
        reveal: true
      - load_var: commit-sha
        file: instana-agent-docker-git/.git/short_ref
        reveal: true
      - in_parallel:
          fail_fast: true
          steps:
            - put: codebuild-static
              params:
                source_version: ((.:s3-artifact-version))
                env_var_overrides:
                  ARCH: x86
                  DOWNLOAD_KEY: ((download-key))
                  FLAVOR: static
                  VERSION: changeme
                  BRANCH: ((.:commit-sha))
                  COMMIT_SHA: ((.:commit-sha))
                  TARGETPLATFORM: linux/amd64
            - put: codebuild-dynamic
              params:
                source_version: ((.:s3-artifact-version))
                env_var_overrides:
                  ARCH: x86
                  DOWNLOAD_KEY: ((download-key))
                  FLAVOR: dynamic
                  VERSION: changeme
                  BRANCH: ((.:commit-sha))
                  COMMIT_SHA: ((.:commit-sha))
                  TARGETPLATFORM: linux/amd64
      - in_parallel:
          fail_fast: true
          steps:
            - put: agent-dynamic-x86
              params:
                  image: codebuild-dynamic/artifacts/image.tar
                  additional_tags: codebuild-dynamic/artifacts/tag
            - put: agent-static-x86
              params:
                  image: codebuild-static/artifacts/image.tar
                  additional_tags: codebuild-static/artifacts/tag

  - name: arm64-build
    public: true
    plan:
      - get: instana-agent-docker-git
        trigger: true
        passed: [ prepare-build-bundle ]
      - get: build-bundle
        trigger: true
        passed: [ prepare-build-bundle ]
      - load_var: s3-artifact-version
        file: build-bundle/version
        reveal: true
      - load_var: commit-sha
        file: instana-agent-docker-git/.git/short_ref
        reveal: true
      - in_parallel:
          fail_fast: true
          steps:
            - put: codebuild-static
              params:
                source_version: ((.:s3-artifact-version))
                env_var_overrides:
                  ARCH: arm64
                  DOWNLOAD_KEY: ((download-key))
                  FLAVOR: static
                  VERSION: changeme
                  BRANCH: ((.:commit-sha))
                  COMMIT_SHA: ((.:commit-sha))
                  TARGETPLATFORM: linux/arm64
            - put: codebuild-dynamic
              params:
                source_version: ((.:s3-artifact-version))
                env_var_overrides:
                  ARCH: arm64
                  DOWNLOAD_KEY: ((download-key))
                  FLAVOR: dynamic
                  VERSION: changeme
                  BRANCH: ((.:commit-sha))
                  COMMIT_SHA: ((.:commit-sha))
                  TARGETPLATFORM: linux/arm64
      - in_parallel:
          fail_fast: true
          steps:
            - put: agent-dynamic-aarch64
              params:
                  image: codebuild-dynamic/artifacts/image.tar
                  additional_tags: codebuild-dynamic/artifacts/tag
            - put: agent-static-aarch64
              params:
                  image: codebuild-static/artifacts/image.tar
                  additional_tags: codebuild-static/artifacts/tag

  - name: s390x-build
    public: true
    plan:
      - get: instana-agent-docker-git
        trigger: true
        passed: [ prepare-build-bundle ]
      - get: build-bundle
        trigger: true
        passed: [ prepare-build-bundle ]
      - load_var: s3-artifact-version
        file: build-bundle/version
        reveal: true
      - load_var: commit-sha
        file: instana-agent-docker-git/.git/short_ref
        reveal: true
      - in_parallel:
          fail_fast: true
          steps:
            - put: codebuild-static
              params:
                source_version: ((.:s3-artifact-version))
                env_var_overrides:
                  ARCH: s390x
                  DOWNLOAD_KEY: ((download-key))
                  FLAVOR: static
                  VERSION: changeme
                  BRANCH: ((.:commit-sha))
                  COMMIT_SHA: ((.:commit-sha))
                  TARGETPLATFORM: linux/s390x
            - put: codebuild-dynamic
              params:
                source_version: ((.:s3-artifact-version))
                env_var_overrides:
                  ARCH: s390x
                  DOWNLOAD_KEY: ((download-key))
                  FLAVOR: dynamic
                  VERSION: changeme
                  BRANCH: ((.:commit-sha))
                  COMMIT_SHA: ((.:commit-sha))
                  TARGETPLATFORM: linux/s390x
      - in_parallel:
          fail_fast: true
          steps:
            - put: agent-dynamic-s390x
              params:
                  image: codebuild-dynamic/artifacts/image.tar
                  additional_tags: codebuild-dynamic/artifacts/tag
            - put: agent-static-s390x
              params:
                  image: codebuild-static/artifacts/image.tar
                  additional_tags: codebuild-static/artifacts/tag
  - name: build-multiarch
    max_in_flight: 1
    plan:
      - get: instana-agent-docker-git
        trigger: true
        passed: [ s390x-build, arm64-build, x86-build ]
      - get: codebuild-dynamic
        passed: [ arm64-build ]
      - load_var: commit-sha
        file: instana-agent-docker-git/.git/short_ref
        reveal: true
      - task: build-dynamic-multiarch-manifest
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: karlkfi/concourse-dcind
          inputs:
            - name: instana-agent-docker-git
            - name: codebuild-dynamic
          params:
            DOCKER_CLI_EXPERIMENTAL: enabled
          run:
            path: entrypoint.sh
            args:
              - bash
              - -ceux
              - |
                set -e
                echo '((project-berlin-tests-gcp-instana-qa))' > key.json
                cat key.json | docker login -u _json_key --password-stdin https://gcr.io

                docker manifest create "gcr.io/instana-agent-qa/instana-agent-docker:((.:commit-sha))" \
                  --amend "gcr.io/instana-agent-qa/instana-agent-docker:((.:commit-sha))-amd64-dynamic" \
                  --amend "gcr.io/instana-agent-qa/instana-agent-docker:((.:commit-sha))-arm64-dynamic"

                docker manifest push "gcr.io/instana-agent-qa/instana-agent-docker:((.:commit-sha))"
