FROM s390x/ubuntu:18.04

ENV LANG=C.UTF-8 \
    GOMPLATE_VERSION="3.4.1" \
    GOMPLATE_SHA256="900efefc9691bdccd46f77cec43f74066709c5be60364ffb160bc76658a97313  v3.4.1.tar.gz"

RUN apt-get update && \
    apt-get install -y wget golang make && \
    mkdir -p /root/go/src/github.com/hairyhenderson && \
    cd /root/go/src/github.com/hairyhenderson && \
    wget https://github.com/hairyhenderson/gomplate/archive/v${GOMPLATE_VERSION}.tar.gz && \
    echo "${GOMPLATE_SHA256}" | sha256sum --check && \
    tar xzf v${GOMPLATE_VERSION}.tar.gz && \
    mv gomplate-${GOMPLATE_VERSION} gomplate && \
    cd gomplate/ && make && cp bin/gomplate /usr/bin/gomplate && \
    gomplate --version

WORKDIR /root

ENTRYPOINT ["/bin/bash"]

# get the gomplate binary by running `./build_s390x_gomplate.sh`
