FROM s390x/ubuntu:20.04

ENV LANG=C.UTF-8 \
    GOMPLATE_VERSION="3.8.0" \
    GOMPLATE_SHA256="d32817821a7b083b0aeadf29c2aea17e3384b6b619f3a6285150db1914b94c89  v3.8.0.tar.gz"

RUN apt-get update && \
    apt-get install -y wget golang make && \
    mkdir -p /root/go/src/github.com/hairyhenderson && \
    cd /root/go/src/github.com/hairyhenderson && \
    wget https://github.com/hairyhenderson/gomplate/archive/v${GOMPLATE_VERSION}.tar.gz && \
    echo "${GOMPLATE_SHA256}" | sha256sum --check && \
    tar xzf v${GOMPLATE_VERSION}.tar.gz && \
    mv gomplate-${GOMPLATE_VERSION} gomplate && \
    cd gomplate/ && make && cp bin/gomplate /usr/bin/gomplate && \
    gomplate --version

WORKDIR /root

ENTRYPOINT ["/bin/bash"]

# get the gomplate binary by running `./build_s390x_gomplate.sh`
