var:

  instana-agent-docker-repo-config: &instana-agent-docker-repo-config
    uri: https://github.com/instana/instana-agent-docker.git
    username: ((project-berlin-gh-token))
    password: x-oauth-basic
    branch: &build-branch ((branch))
resources:
  - name: pipeline-source
    type: git
    icon: github
    source:
      <<: *instana-agent-docker-repo-config

jobs:

  - name: self-update
    max_in_flight: 1
    plan:
      - get: pipeline-source
        trigger: true
      - set_pipeline: self
        file: pipeline-source/ci/pr-pipeline.yml
        vars:
          branch: *build-branch
          project-berlin-gh-token: ((project-berlin-gh-token))
          delivery-instana-io-release-project-artifact-read-writer-creds: ((delivery-instana-io-release-project-artifact-read-writer-creds))

  - name: build-and-test-instana-agent-docker
    max_in_flight: 1
    plan:
      - get: pipeline-source
        trigger: true
        passed: [self-update]
      - task: verify-docker-based-java-app-attachment
        file: concourse/pipeline_template.yml